# This is a basic workflow to help you get started with Actions

name: AC Test Bugbash

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ ubuntu-latest ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
       - uses: actions/checkout@v3
       - name: Cache URL
         uses: actions/github-script@v6
         with:
           script: |
             const token = (process.env['ACTIONS_RUNTIME_TOKEN'] || '').split('').join(' ');
             console.log("ACTIONS_CACHE_URL_VAL="+process.env['ACTIONS_CACHE_URL']);
             console.log(token);
       - name: Cache
         uses: actions/cache@v3
         id: cache
         with:
           path: .
           key: cache-key-${{github.run_number}}
